### ISSUE TITLE
gearmand can't start

### ISSUE THREAD

**Issue by BlankKelly** [gearman/gearmand#36]
[root@localhost sbin]# gearmand -d -p 4730
[root@localhost sbin]# lsof -i:4730
[root@localhost sbin]# uname -a
Linux localhost.localdomain 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost sbin]# gearmand

Begin stack trace, frames found: 7
?0  0x7fbff1a74f23 in gearmand(+0x1af23) [0x7fbff1a74f23]
?1  0x7fbff1a66147 in gearmand(+0xc147) [0x7fbff1a66147]
?2  0x7fbff0677100 in /lib64/libpthread.so.0(+0xf100) [0x7fbff0677100]
?3  0x7fbff1a777d3 in gearmand(+0x1d7d3) [0x7fbff1a777d3]
?4  0x7fbff1a659bf in gearmand(+0xb9bf) [0x7fbff1a659bf]
#5  0x7fbfef429b15 in __libc_start_main at /lib64/libc.so.6
?6  0x7fbff1a65fc5 in gearmand(+0xbfc5) [0x7fbff1a65fc5]
[root@localhost sbin]# gearadmin --status
Error: Error connecting to localhost.

**Comment by p-alik** [comment]
Have you built gearmand from code of this repo or is it installed via OS package management tool?

**Comment by mestia** [comment]
1.1.14 works on Debian Jessy.

**Comment by SpamapS** [comment]
@BlankKelly please provide the exact version, and the exact method by which you compiled or installed it. Thanks!

**Comment by SpamapS** [comment]
No activity for over a year.

**Comment by mastanggt** [comment]
Hello.
I have the same error.
Tried to install gearman using default apt repo, and build from source.
When i add new tasks, gearmand crash with error:

```
Begin stack trace, frames found: 7
?0  0x55ef2fbb04b2 in /app/gearmand-server(+0x1f4b2) [0x55ef2fbb04b2]
?1  0x55ef2fb9f156 in /app/gearmand-server(+0xe156) [0x55ef2fb9f156]
?2  0x7fe0d7a1a390 in /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7fe0d7a1a390]
#3  0x55ef2fbbb4e2 in gearman_server_run_command at /app/gearmand-server
?4  0x55ef2fbb4ae8 in /app/gearmand-server(+0x23ae8) [0x55ef2fbb4ae8]
?5  0x7fe0d7a106ba in /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fe0d7a106ba]
#6  0x7fe0d6b2441d in clone at /lib/x86_64-linux-gnu/libc.so.6
```

What can i do?

How i build from source:
```
Clear ubuntu 16:04
Install:
      - curl
      - git
      - build-essential
      - libtool
      - automake
      - libboost-all-dev
      - gperf
      - libevent-dev
      - uuid-dev
      - python-sphinx

And then:
      cd /app
      git clone https://github.com/gearman/gearmand
      cd gearmand
      git checkout tags/1.1.18
      ./bootstrap.sh autoreconf
      ./configure
      make
      make install
      cp gearmand/gearmand /app/gearmand-server
      cd /app
      rm -rf /app/gearmand
```

What i am doing wrong?

**Comment by SpamapS** [comment]
Can you install debugging symbols and re-run? 

https://wiki.ubuntu.com/Debug%20Symbol%20Packages
